config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'up' => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :reservations
    get :calendar, to: 'reservations#calendar'
    root to: 'reservations#index'
  end

  resources :contacts

  get :contact,      path: 'kontakt',   to: 'pages#contact'
  get :galerie,      path: 'galerie',   to: 'pages#galerie'
  get :neighborhood, path: 'okoli',     to: 'pages#neighborhood'
  get :price,        path: 'cenik',     to: 'pages#price'
  get :reservation,  path: 'rezervace', to: 'pages#reservation'
  get :rooms,        path: 'pokoje',    to: 'pages#rooms'
  get :wedding,      path: 'svatba',    to: redirect("/svatba-ela-martin.pdf", status: 302)

  root to: 'pages#home'
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  validates :email, format: { with: Devise.email_regexp, allow_blank: true }
  validates :date_from, :date_to, :state, presence: true

  scope :ordered, -> { order(date_from: :asc) }
end

app/controllers/admin/reservations_controller.rb
module Admin
  class ReservationsController < AdminController
    before_action :set_reservation, only: %i[show edit update destroy]

    def index
      @reservations = Reservation.ordered
    end

    def calendar
      @reservations = Reservation.ordered
    end

    def show; end

    def new
      @reservation = Reservation.new
    end

    def edit; end

    def create
      @reservation = Reservation.new(reservation_params)

      if @reservation.save
        redirect_to admin_reservations_path, notice: 'Rezervace byla úspěšně vytvořena.'
      else
        render :new
      end
    end

    def update
      if @reservation.update(reservation_params)
        redirect_to admin_reservations_path, notice: 'Rezervace byla úspěšně upravena.'
      else
        render :edit
      end
    end

    def destroy
      @reservation.destroy
      redirect_to admin_reservations_path, notice: 'Rezervace byla úspěšně smazána.'
    end

    private

    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(
        :date_from, :date_to, :name, :email, :notice, :state, :phone_number
      )
    end
  end
end

app/views/admin/reservations/_form.html.slim
= simple_form_for([:admin, @reservation]) do |f|
  = f.error_notification

  .form-inputs
    .row
      .col-md-2 = f.input :date_from, as: :string, input_html: { class: "datepicker" }
      .col-md-2 = f.input :date_to, as: :string, input_html: { class: "datepicker" }
      .col-md-2 = f.input :state, collection: [['Zarezervovaná', :booked], ['Potvrzená', :confirmed]], include_blank: false
      .col-md-3 = f.input :phone_number
      .col-md-3 = f.input :email
    .row
      .col-md-4 = f.input :name
      .col-md-8 = f.input :notice, as: :string

  .form-actions
    = f.button :submit, class: 'btn btn-success'
    = link_to 'Zpět', admin_reservations_path, class: 'btn btn-info'

app/views/admin/reservations/calendar.html.slim
h1 Rezervace

.container
  = render 'calendar'

app/views/admin/reservations/edit.html.slim
h1 Úprava rezervace

== render 'form'

app/views/admin/reservations/index.html.slim
h1 Seznam rezervací

table.table
  thead
    tr
      th = Reservation.human_attribute_name :date_from
      th = Reservation.human_attribute_name :date_to
      th = Reservation.human_attribute_name :name
      th = Reservation.human_attribute_name :phone_number
      th = Reservation.human_attribute_name :notice
      th

  tbody
    - @reservations.each do |reservation|
      tr
        td = l reservation.date_from
        td = l reservation.date_to
        td = reservation.name
        td = reservation.phone_number
        td = reservation.notice
        td
          = link_to 'Upravit', edit_admin_reservation_path(reservation), class: 'btn btn-primary'
          = link_to 'Smazat', admin_reservation_path(reservation), data: {confirm: 'Jste si jistí?'}, method: :delete, class: 'btn btn-danger'
br

= link_to 'Přidat rezevaci', new_admin_reservation_path, class: 'btn btn-success'

app/views/admin/reservations/new.html.slim
h1 Nová rezervace

== render 'form'