config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'up' => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :reservations
    get :calendar, to: 'reservations#calendar'
    root to: 'reservations#index'
  end

  resources :contacts

  get :contact,      path: 'kontakt',   to: 'pages#contact'
  get :galerie,      path: 'galerie',   to: 'pages#galerie'
  get :neighborhood, path: 'okoli',     to: 'pages#neighborhood'
  get :price,        path: 'cenik',     to: 'pages#price'
  get :reservation,  path: 'rezervace', to: 'pages#reservation'
  get :rooms,        path: 'pokoje',    to: 'pages#rooms'
  get :wedding,      path: 'svatba',    to: redirect("/svatba-ela-martin.pdf", status: 302)

  root to: 'pages#home'
end

app/views/admin/partials/_menu.html.slim
nav.admin.navbar.navbar-inverse role='navigation'
  .container
    .navbar-header
      button.navbar-toggle.collapsed data-target='#bs-example-navbar-collapse-1' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Umago.cz', root_path, target: :blank, class: 'navbar-brand'

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li = link_to 'Rezervace', admin_reservations_path
        li = link_to 'Kalendář', admin_calendar_path
      ul.nav.navbar-nav.navbar-right
        li = link_to 'Odhlásit se', destroy_user_session_path, method: :delete