config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'up' => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :reservations
    get :calendar, to: 'reservations#calendar'
    root to: 'reservations#index'
  end

  resources :contacts

  get :contact,      path: 'kontakt',   to: 'pages#contact'
  get :galerie,      path: 'galerie',   to: 'pages#galerie'
  get :neighborhood, path: 'okoli',     to: 'pages#neighborhood'
  get :price,        path: 'cenik',     to: 'pages#price'
  get :reservation,  path: 'rezervace', to: 'pages#reservation'
  get :rooms,        path: 'pokoje',    to: 'pages#rooms'
  get :wedding,      path: 'svatba',    to: redirect("/svatba-ela-martin.pdf", status: 302)

  root to: 'pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def calendar_date_class(reservations, date)
    current = reservations.select { |r| (r.date_from..r.date_to).cover?(date) }
    case current.size
    when 1
      reservation = current.first
      if    date == reservation.date_from  then "start-#{reservation.state}"
      elsif date == reservation.date_to    then "end-#{reservation.state}"
      else reservation.state
      end
    when 2
      first, second = current
      if first.state == second.state
        first.state
      else
        "end-#{first.state} start-#{second.state}"
      end
    end
  end
end

app/views/application/_calendar.html.slim
.booking-calendar.row
  - start = Date.today.beginning_of_month
  - [*0...12].each do |month|
    .month-calendar.col-sm-4
      - date = start + month.months
      = calendar(year: date.year, month: date.month) do |d|
        - [d.mday, class: calendar_date_class(@reservations, d)]

app/views/application/_carousel.html.slim
.slider-wrapper
  .text-holder
    h1 Ubytování na samotě
    h2 Nedaleko centra města Náchod
    = link_to 'Prohlédnout si pokoje', rooms_path

  ul.bx-slider
    li = image_tag 'header/01.jpg'
    li = image_tag 'header/02.jpg'
    li = image_tag 'header/03.jpg'

app/views/application/_flashes.html.slim
#flash
  - flash.each do |key, value| 
    div id="flash-#{ key }"
      = value

app/views/application/_footer_box.html.slim
.contact
  .row
    .google-map.col-md-6 = render 'gmap'

    .address.col-md-6
      img src='https://bookingawards.simoncelen.net/1/2/9/1293214/social_media.png' width='200' height='200' align='right'

      h3 Kontaktujte nás
      ul.list-unstyled
        li Milan Magnusek
        li Ve Smrčinách 60
        li 547 01 Náchod
        li
        | (+420) 737 816 210
        li = mail_to 'umago@seznam.cz'

.copyright
  p
    => link_to 'Administrace', admin_root_path
    | Umago.cz all rights reserved
    =< Date.today.year
    br
    | Milan Magnusek, Ve Smrčinách 60, NÁCHOD 547 01

app/views/application/_gmap.html.erb
<iframe
  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d10168.814789637145!2d16.20093360288835!3d50.41867633417048!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x470e6f816b510fa3%3A0x60e82e1e4eed8d79!2zVmUgU21yxI1pbsOhY2ggNjAsIDU0NyAwMSBOw6FjaG9k!5e0!3m2!1scs!2scz!4v1425208904439"
  frameborder="0">
</iframe>

app/views/application/_navigation.html.slim
nav
  ul.nav.list-inline.d-flex.justify-content-center
    li = link_to 'Pokoje',      rooms_path
    li = link_to 'Okolí',       neighborhood_path
    li = link_to 'Fotogalerie', galerie_path
    li.logo
      = link_to root_path
        span UMA
        span.green GO
      small Ubytování v soukromí
    li = link_to 'Ceník',     price_path
    li = link_to 'Volné termíny', reservation_path